modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="usefulstones" #mandatory
version="1.0.1" #mandatory
displayName="ยง1Useful Stones" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="http://example.com/" #optional
logoFile="logo.png" #optional
credits="Thanks to Everyone :D" #optional
authors="Eno_gamer10" #optional
description='''
This is a simple mod who add bluestone, a very useful dust...
'''
[[dependencies.usefulstones]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.usefulstones]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
